updated brew library

diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -1,72 +1,70 @@
 #!/bin/bash
 
-run_brew() {
+desired_formulae=(
+'coreutils' # GNU core utilities (those that come with OS X are outdated)
+'bash'
+'git'
+'ack'
+'bash-completion'
+'jpeg'
+'macvim --override-system-vim'
+'node'
+'optipng'
+'phantomjs'
+'tree'
+'wget'
+'gist'
+'ctags'
+'webkit2png'
+'libjpeg'
+'rename'
+'tmux'
+'the_silver_searcher'
+'bash-completion'
+'reattach-to-user-namespace'
+)
 
-    # Check for Homebrew
-    if type_exists 'brew'; then
-        e_header "Updating Homebrew..."
-        # Use the latest version of Homebrew
-        brew update
-        [[ $? ]] && e_success "Done"
+source ~/.dotfiles/lib/functions
 
-        e_header "Updating any existing Homebrew formulae..."
-        # Upgrade any already-installed formulae
-        brew upgrade
-        [[ $? ]] && e_success "Done"
+# Check for Homebrew
+if ! type_exists 'brew'; then
+  echo
+  e_error "Error: Homebrew not found."
+  echo "Installing Homebrew..."
+  ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
+fi
 
-        e_header "Checking status of desired Homebrew formulae..."
-        local list_formulae
-        local -a missing_formulae
-        local -a desired_formulae=(
-            'coreutils' # GNU core utilities (those that come with OS X are outdated)
-            'bash'
-            'git'
-            'ack'
-            'bash-completion'
-            'jpeg'
-            'macvim --override-system-vim'
-            'node'
-            'optipng'
-            'phantomjs'
-            'tree'
-            'wget'
-      	    'gist'
-            'ctags'
-            'webkit2png'
-            'libjpeg'
-            'rename'
-            'tmux'
-            'the_silver_searcher'
-            'bash-completion'
-            'reattach-to-user-namespace'
-        )
+if type_exists 'brew'; then
+  e_header "Updating Homebrew..."
+  # Use the latest version of Homebrew
+  brew update
+  [[ $? ]] && e_success "Done"
 
-        for index in ${!desired_formulae[*]}
-        do
-            if ! formula_exists ${desired_formulae[$index]}; then
-                # Store the name (and options) of every missing formula
-                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
-            fi
-        done
+  e_header "Updating any existing Homebrew formulae..."
+  # Upgrade any already-installed formulae
+  brew upgrade
+  [[ $? ]] && e_success "Done"
 
-        if [[ "$missing_formulae" ]]; then
-            # Convert the array of missing formula into a list of space-separate strings
-            list_formulae=$( printf "%s " "${missing_formulae[@]}" )
-
-            e_header "Installing missing Homebrew formulae..."
-            # Install all missing formulae
-            brew install $list_formulae
-
-            [[ $? ]] && e_success "Done"
-        fi
-
-        # Remove outdated versions from the Cellar
-        # brew cleanup
-    else
-        echo
-        e_error "Error: Homebrew not found."
-        echo "Aborting..."
-        exit
+  e_header "Checking status of desired Homebrew formulae..."
+  for index in ${!desired_formulae[*]}
+  do
+    if ! formula_exists ${desired_formulae[$index]}; then
+      # Store the name (and options) of every missing formula
+      missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
     fi
+  done
 
-}
+  if [[ "$missing_formulae" ]]; then
+    # Convert the array of missing formula into a list of space-separate strings
+    list_formulae=$( printf "%s " "${missing_formulae[@]}" )
+
+    e_header "Installing missing Homebrew formulae..."
+    # Install all missing formulae
+    brew install $list_formulae
+
+    [[ $? ]] && e_success "Done"
+  fi
+
+  # Remove outdated versions from the Cellar
+  # brew cleanup
+fi
