update libs

diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -1,41 +1,68 @@
-# Check for Homebrew
-if test ! $(which brew)
-then
-  echo "  x Homebrew not found. Please install it running this command:"
-  echo '    ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"'
-  exit
-else
-  echo "  + Homebrew found."
-fi
+#!/bin/bash
 
-# Make sure we’re using the latest Homebrew
-brew update
+run_brew() {
 
-# Upgrade any already-installed formulae
-brew upgrade
+    # Check for Homebrew
+    if type_exists 'brew'; then
+        e_header "Updating Homebrew..."
+        # Use the latest version of Homebrew
+        brew update
+        [[ $? ]] && e_success "Done"
 
-# Install GNU core utilities (those that come with OS X are outdated)
-brew install coreutils
-# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
-brew install findutils
-# Install Bash 4
-brew install bash
+        e_header "Updating any existing Homebrew formulae..."
+        # Upgrade any already-installed formulae
+        brew upgrade
+        [[ $? ]] && e_success "Done"
 
-# Install everything else
-brew install git
-brew install bash-completion
-brew install libjpeg
-brew install macvim --override-system-vim
-brew install optipng
-brew install phantomjs
-brew install tree
-brew install wget
-brew install ack
-brew install node
-brew install rename
-brew install webkit2png
-brew install gist
-brew install ctags
+        e_header "Checking status of desired Homebrew formulae..."
+        local list_formulae
+        local -a missing_formulae
+        local -a desired_formulae=(
+            'coreutils' # GNU core utilities (those that come with OS X are outdated)
+            'bash'
+            'git'
+            'ack'
+            'bash-completion'
+            'jpeg'
+            'macvim --override-system-vim'
+            'node'
+            'optipng'
+            'phantomjs'
+            'tree'
+            'wget'
+	    'gist'
+            'ctags'
+            'webkit2png'
+            'libjpeg'
+            'rename'
+        )
 
-# Remove outdated versions from the Cellar
-# brew cleanup
+        for index in ${!desired_formulae[*]}
+        do
+            if ! formula_exists ${desired_formulae[$index]}; then
+                # Store the name (and options) of every missing formula
+                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
+            fi
+        done
+
+        if [[ "$missing_formulae" ]]; then
+            # Convert the array of missing formula into a list of space-separate strings
+            list_formulae=$( printf "%s " "${missing_formulae[@]}" )
+
+            e_header "Installing missing Homebrew formulae..."
+            # Install all missing formulae
+            brew install $list_formulae
+
+            [[ $? ]] && e_success "Done"
+        fi
+
+        # Remove outdated versions from the Cellar
+        # brew cleanup
+    else
+        echo
+        e_error "Error: Homebrew not found."
+        echo "Aborting..."
+        exit
+    fi
+
+}
