give user the option to stow module within the install script

diff --git a/shell/bin/dots b/shell/bin/dots
--- a/shell/bin/dots
+++ b/shell/bin/dots
@@ -33,6 +33,92 @@ _areuthere() {
   command -v "$1" >/dev/null;
 }
 
+stow-module() {
+  if [[ $link ]]; then
+    if stow -n -t "$HOME" "$module" 2>/dev/null; then
+      _run stow -R -t "$HOME" "$module"
+    else
+      conflicts=$(stow -n -t "$HOME" "$module" 2>&1 |
+                    awk '/\* existing target is neither/ {print "~/" $NF};\
+                      /\* existing target is stowed/ {print "~/" $(NF-2)}')
+
+      if [[ $yes ]]; then
+        choice=y
+      else
+        echo -e "  ${red}CONFLICTS:${nc} $(echo "$conflicts" | tr '\n' ' ')"
+        read -n 1 -rp "  Overwrite? [y/n] " choice
+        echo
+      fi
+      case $choice in
+        y|Y) for filename in $conflicts; do
+               # Remove conflictive files
+               [[ -f $HOME/$filename || -L $HOME/$filename ]] && _run rm -f "$HOME/$filename"
+             done
+             _run stow -t "$HOME" "$module"
+             ;;
+        *)   PREFIX="${red}ABORTED:${nc} " DRYRUN=1 _run stow -t "$HOME" "$module"
+             register=
+             ;;
+      esac
+    fi
+  fi
+}
+
+restow-module() {
+  [[ $link ]] && _run stow -R -t "$HOME" "$module" # Restow
+}
+
+isinstalled() {
+  case "$OSTYPE" in
+    darwin*)
+      return $(formula_exists $1)
+      ;;
+  esac
+  return 0
+}
+
+installcmd() {
+  $installcmd $1
+}
+
+install-deps() {
+  local osdepsvar="${PACKAGE_MANAGER}_deps"
+  local osdeps="${osdepsvar}[@]"
+  local deps_to_install=()
+
+  # prevent install deps in unsupported package managers
+  [[ ${SUPPORTED_PACKAGE_MANAGERS[@]} =~ ${PACKAGE_MANAGER} ]] || return 1
+
+  [[ -n $basedeps ]] && deps_to_install=("${deps_to_install[@]}" "${basedeps[@]}")
+
+  if [[ -n ${!osdepsvar} ]]; then
+    deps_to_install=("${deps_to_install[@]}" "${!osdeps}")
+  elif [[ -n $deps ]]; then
+    deps_to_install=("${deps_to_install[@]}" "${deps}")
+  fi
+
+  for dep in "${deps_to_install[@]}"; do
+    # Skip installation if package is already installed
+    isinstalled "$dep" && continue
+    installcmd "$dep"
+  done
+}
+
+pop-and-missing() {
+  local pkg=$1
+  local pm=$2
+  local depsclone=$deps
+  # fail if the available PM is not the same as the passed one
+  [[ $# -eq 2 && $pm != ${PACKAGE_MANAGER} ]] && return 1
+  # fail when deps is empty
+  [[ $deps ]] || return 1
+  # Pop pkg from array
+  deps=( ${deps[@]#$pkg} )
+  # Compare arrays and fail if no pkg was popped
+  [[ ${depsclone[@]} == ${deps[@]} ]] && return 1
+  ! is_callable "$pkg"
+}
+
 
 ### PREAMBLE
 
@@ -71,6 +157,38 @@ source "$utilspath"
 [[ -L "$HOME"/.stow-global-ignore ]] || ln -s "$DOTFILES"/.stow-global-ignore "$HOME"/.stow-global-ignore
 
 progname=$(basename "$0")
+
+case "$OSTYPE" in
+  darwin*)
+    export PACKAGE_MANAGER=brew
+    installcmd="brew install"
+    ;;
+  linux*)
+    if [[ -f /etc/arch-release ]]; then
+      export PACKAGE_MANAGER=pacman
+      installcmd="sudo pacman --needed --noconfirm -S"
+    elif [[ -f /etc/fedora-release ]]; then
+      if is_callable dnf; then
+        export PACKAGE_MANAGER=dnf
+        installcmd="sudo dnf install -y"
+      else
+        export PACKAGE_MANAGER=yum
+        installcmd="sudo yum -y install"
+      fi
+    elif [[ -f /etc/debian-version ]]; then
+      if is_callable apt; then
+        export PACKAGE_MANAGER=apt
+        installcmd="apt install -y"
+      else
+        export PACKAGE_MANAGER=apt-get
+        installcmd="apt-get install -y"
+      fi
+    elif [[ -f /etc/SuSE-release ]]; then
+      export PACKAGE_MANAGER=zypper
+      installcmd="zypper install -y"
+    fi
+    ;;
+esac
 
 
 ### COMMANDS
@@ -242,7 +360,6 @@ EOL
 
     modulepath="${DOTFILES}/$module"
     updatepath="$modulepath/update"
-    [[ $link ]] && _run stow -R -t "$HOME" "$module" # Restow
 
     # run update script in a subshell, inherits everything from the current
     # script but do not transmit any change back
@@ -308,35 +425,6 @@ EOL
     register=1
 
     echo -e "${green}» ${module}${nc}"
-
-    if [[ $link ]]; then
-      if stow -n -t "$HOME" "$module" 2>/dev/null; then
-        _run stow -R -t "$HOME" "$module"
-      else
-        conflicts=$(stow -n -t "$HOME" "$module" 2>&1 |
-                      awk '/\* existing target is neither/ {print "~/" $NF};\
-                        /\* existing target is stowed/ {print "~/" $(NF-2)}')
-
-        if [[ $yes ]]; then
-          choice=y
-        else
-          echo -e "  ${red}CONFLICTS:${nc} $(echo "$conflicts" | tr '\n' ' ')"
-          read -n 1 -rp "  Overwrite? [y/n] " choice
-          echo
-        fi
-        case $choice in
-          y|Y) for filename in $conflicts; do
-                 # Remove conflictive files
-                 [[ -f $HOME/$filename || -L $HOME/$filename ]] && _run rm -f "$HOME/$filename"
-               done
-               _run stow -t "$HOME" "$module"
-               ;;
-          *)   PREFIX="${red}ABORTED:${nc} " DRYRUN=1 _run stow -t "$HOME" "$module"
-               register=
-               ;;
-        esac
-      fi
-    fi
 
     linkpath="${ENABLED_DIR}/${module}"
     modulepath="$DOTFILES/$module"
